# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest requests
        sudo apt-get install python-libtorrent
        sudo python test.py
        ls -las
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Upload
      uses: Difegue/action-megacmd@master
      with:
        args: put /Vikings S01 Complete Season 1 EXTENDED BluRay 720p x265 HEVC [nate_666]/ /
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
